"""
Governance Reason Codes Registry

Centralizes all standardized auditing reason codes to ensure consistency 
across policy evaluation, state transitions, anomaly detection, and the audit trail.
"""

# Core Policy/Verification codes
POLICY_FAIL_CLOSED = "POLICY_FAIL_CLOSED"
PROVIDER_NOT_APPROVED = "PROVIDER_NOT_APPROVED"
DECEPTIVE_CONTENT = "DECEPTIVE_CONTENT"
QUALITY_CHECKS_FAILED = "QUALITY_CHECKS_FAILED"

# Review & Approval codes
MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
SEPARATION_OF_DUTIES_VIOLATION = "SEPARATION_OF_DUTIES_VIOLATION"
REVIEW_APPROVED = "REVIEW_APPROVED"
REVIEW_REJECTED = "REVIEW_REJECTED"

# Exception/Retention codes
EXC_EXPIRY = "EXC_EXPIRY"
RETENTION_EXPIRY = "RETENTION_EXPIRY"
LEGAL_HOLD_PLACED = "LEGAL_HOLD_PLACED"
LEGAL_HOLD_RELEASED = "LEGAL_HOLD_RELEASED"

# Security & Workspace codes
ACCESS_DENIED = "ACCESS_DENIED"

# Incident & Anomaly codes
REPEATED_BLOCKS_ANOMALY = "REPEATED_BLOCKS_ANOMALY"
PROVIDER_POLICY_DRIFT = "PROVIDER_POLICY_DRIFT"
