"""initial_schema_with_indexes

Revision ID: c4b95126e85b
Revises: 
Create Date: 2026-07-13 00:45:20.088583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b95126e85b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_governance_assets_governance_state'), 'governance_assets', ['governance_state'], unique=False)
    op.create_index(op.f('ix_governance_assets_retention_expires_at'), 'governance_assets', ['retention_expires_at'], unique=False)
    op.create_index(op.f('ix_governance_events_action'), 'governance_events', ['action'], unique=False)
    op.create_index(op.f('ix_governance_exceptions_status'), 'governance_exceptions', ['status'], unique=False)
    op.add_column('governance_review_tasks', sa.Column('secondary_approved_by', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('governance_review_tasks', 'secondary_approved_by')
    op.drop_index(op.f('ix_governance_exceptions_status'), table_name='governance_exceptions')
    op.drop_index(op.f('ix_governance_events_action'), table_name='governance_events')
    op.drop_index(op.f('ix_governance_assets_retention_expires_at'), table_name='governance_assets')
    op.drop_index(op.f('ix_governance_assets_governance_state'), table_name='governance_assets')
    # ### end Alembic commands ###
